name: CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "Readme.md"
      - "helm/**"
      - "k8s/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "DB_HOST=${{ secrets.DATABASE_URL }}" >> .env
          echo "DB_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build
        run: npm run build

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create env file
        run: |
          echo "DB_HOST=${{ secrets.DATABASE_URL }}" >> .env
          echo "DB_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwcportal:${{github.run_id}}

      - name: Trigger Infrastructure Repo Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Vraj209/infra-kwc-portal-new
          event-type: update-helm-chart
          token: ${{ secrets.TOKEN }}
          client-payload: '{"imageTag": "${{ github.run_id }}"}'
